name: CI

env:
  SITE_URL: ${{ vars.SITE_URL }}

on:
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Yarn
        uses: threeal/setup-yarn-action@v2

      - run: cp .env.example .env
      - run: yarn install
      - run: yarn lint
      - run: yarn tsc
      - run: yarn build
