name: Node.js CI

on:
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: cp .env.example .env
      - run: yarn install
      - run: yarn lint
      - run: yarn tsc
      - run: yarn build
